name : PR Validation

on:
  pull_request :
    branches :
      - Branch-a
      - Branch-b

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Check Pull Request Source
      run: |
        if [[ "${{github.base_ref}}" == "main" && "${{github.head_ref}}" == "Branch-a" ]]; then
          echo "Pull request to main from Branch-a: Success!"
        elif [[ "${{github.base_ref}}" == "main" && "${{github.head_ref}}" == "Branch-b" ]]; then
          echo "Pull request to main from Branch-b: Failed"
          exit 1
        else
          echo "PR does not match, Invalid"
          exit 1
        fi
