name : PR Validation

on:
  pull_request :
    branches :
      - Branch-a
      - Branch-b

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Check Pull Request Source
      run: |
        if [[ "${{github.base_ref}}" == "Branch-a" && "${{github.head_ref}}" == "main" ]]; then
          echo "Pull request to Branch-a from main: Success!"
        elif [[ "${{github.base_ref}}" == "Branch-b" && "${{github.head_ref}}" == "main" ]]; then
          echo "Pull request to Branch-b from main: Failed"
          exit 1
        else
          echo "PR does not match, Invalid"
          exit 1
        fi
